target_sources(terra
        PRIVATE
        divergence.hpp
        gradient.hpp
        identity.hpp
        laplace.hpp
        laplace_simple.hpp
        mass.hpp
        prolongation_linear.hpp
        restriction_linear.hpp
        stokes.hpp
        unsteady_advection_diffusion_supg.hpp
        vector_laplace.hpp
        vector_laplace_simple.hpp
        vector_mass.hpp
        div_k_grad.hpp
        div_k_grad_simple.hpp
        wedge_constant_div_k_grad.hpp
        epsilon.hpp
        epsilon_divdiv.hpp
        epsilon_divdiv_kerngen.hpp
        epsilon_divdiv_simple.hpp
        epsilon_divdiv_stokes.hpp
        zero.hpp
        kmass.hpp
	# shear_heating_simple.hpp
        )

add_subdirectory(optimized_laplace)
